#!/usr/bin/bash
# Functions
PUT(){ echo -en "\033[${1};${2}H";}
DRAW(){ echo -en "\033%";echo -en "\033(0";}
WRITE(){ echo -en "\033(B";}
HIDECURSOR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}
tput civis
clear
tput setaf 2
DRAW
echo
#echo "a b c d e f g h i j k l m n o p q r s t u v w x y z"
echo "lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "x                                                                 x"
echo "mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj"
WRITE
#echo "a b c d e f g h i j k l m n o p q r s t u v w x y z"
PUT 4 0
# figlet -f ASCII-Shadow "\   termux" | lolcat -f
figlet -f 4Max "     termux" | lolcat -f
PUT 4 0
viu -a -t -1 -s ~/.termux/imgs/img1.png -h 10 -w 20 -y 1
DRAW
PUT 3 0
tput civis
tput setaf 2
echo "x"
echo "x"
echo "x"
echo "x"
echo "x"
echo "x"
echo "x"
echo "x"
WRITE
PUT 10 50
echo -e "\e[35mBoot Script \e[33m2.0\e[0m"
PUT 12 0
echo
NORM
